print("hello world")
print("he can do evefdfskj")
print("hello world")
print("he can do evefdfskj")
print("hello world")
print("he can do evefdfskj")
print("hello world")
print("he can do evefdfskj")
print("hello world")
print("he can do evefdfskj")
print("hello world")
print("he can do evefdfskj")